-- ============================================================================
-- DATOS DE PRUEBA PARA USUARIOS Y FLUJO DE CITAS
-- Proyecto: Visitas ITR
-- Motor: Oracle Database
--
-- OBJETIVO
-- Crear datos mínimos para probar los accesos de administrador, docente y
-- encargado, además de la relación completa que necesita una cita:
--
-- USUARIOS -> EMPLEADOS (administrador y docente)
-- USUARIOS -> ESTUDIANTE -> ESTUDIANTE_ENCARGADO -> CITA_REUNION (encargado)
--
-- IMPORTANTE
-- 1. Este archivo NO crea, elimina ni modifica tablas o columnas.
-- 2. Los ID son columnas IDENTITY; por eso se omiten en los INSERT.
-- 3. Las llaves relacionadas se recuperan con subconsultas por correo/código.
-- 4. Cada INSERT usa NOT EXISTS para que el script pueda ejecutarse de nuevo
--    sin duplicar los datos de prueba.
-- 5. Las contraseñas están en texto plano únicamente porque la API actual las
--    compara de esa forma. Deben reemplazarse por hashes al implementar la API
--    de autenticación con BCrypt.
-- ============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === 1. Catalogos necesarios para el estudiante ===

INSERT INTO NIVEL (NIVEL)
SELECT 'BACHILLERATO'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM NIVEL
    WHERE UPPER(NIVEL) = 'BACHILLERATO'
);

INSERT INTO ESPECIALIDAD (ESPECIALIDAD)
SELECT 'DESARROLLO DE SOFTWARE'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM ESPECIALIDAD
    WHERE UPPER(ESPECIALIDAD) = 'DESARROLLO DE SOFTWARE'
);

INSERT INTO SECCION_TECNICA (TECNICA)
SELECT 'DS-A'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM SECCION_TECNICA
    WHERE UPPER(TECNICA) = 'DS-A'
);

INSERT INTO GRADO (GRADO, ID_NIVEL, ID_TECNICA, ID_ESPECIALIDAD)
SELECT
    'SEGUNDO AÑO',
    (SELECT MIN(ID_NIVEL)
       FROM NIVEL
      WHERE UPPER(NIVEL) = 'BACHILLERATO'),
    (SELECT MIN(ID_TECNICA)
       FROM SECCION_TECNICA
      WHERE UPPER(TECNICA) = 'DS-A'),
    (SELECT MIN(ID_ESPECIALIDAD)
       FROM ESPECIALIDAD
      WHERE UPPER(ESPECIALIDAD) = 'DESARROLLO DE SOFTWARE')
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM GRADO
    WHERE UPPER(GRADO) = 'SEGUNDO AÑO'
);

INSERT INTO ACADEMICA (ACADEMICA)
SELECT '2-A'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM ACADEMICA
    WHERE UPPER(ACADEMICA) = '2-A'
);

PROMPT === 2. Usuarios para los tres roles de prueba ===

-- Acceso de administrador para el frontend web.
INSERT INTO USUARIOS (USU_EMAIL, USU_PASSWORD, USU_ROL)
SELECT 'admin.prueba@ricaldone.edu.sv', 'Prueba123*', 'ADMINISTRADOR'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM USUARIOS
    WHERE UPPER(USU_EMAIL) = 'ADMIN.PRUEBA@RICALDONE.EDU.SV'
);

-- Acceso de docente para el frontend web y la aplicación de docentes.
INSERT INTO USUARIOS (USU_EMAIL, USU_PASSWORD, USU_ROL)
SELECT 'docente.prueba@ricaldone.edu.sv', 'Prueba123*', 'DOCENTE ACADÉMICO'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM USUARIOS
    WHERE UPPER(USU_EMAIL) = 'DOCENTE.PRUEBA@RICALDONE.EDU.SV'
);

-- La API actual espera que el encargado use el correo institucional asociado
-- al estudiante. Por eso este usuario tiene rol PADRE y luego se enlaza desde
-- ESTUDIANTE.USUARIO_ESTUDIANTE.
INSERT INTO USUARIOS (USU_EMAIL, USU_PASSWORD, USU_ROL)
SELECT 'estudiante.prueba@ricaldone.edu.sv', 'Prueba123*', 'PADRE'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM USUARIOS
    WHERE UPPER(USU_EMAIL) = 'ESTUDIANTE.PRUEBA@RICALDONE.EDU.SV'
);

PROMPT === 3. Perfiles de administrador y docente ===

-- EMPLEADOS conserva actualmente correo y clave, además del registro de
-- USUARIOS. Se colocan los mismos valores para que el inicio de sesión actual
-- no encuentre credenciales contradictorias.
INSERT INTO EMPLEADOS (
    EMP_NOMBRE,
    EMP_APELLIDO,
    EMP_CLAVE,
    EMP_CORREO,
    EMP_ROL,
    USUARIO_EMPLEADO
)
SELECT
    'Ana',
    'Administradora',
    'Prueba123*',
    'admin.prueba@ricaldone.edu.sv',
    'ADMINISTRADOR',
    (SELECT MIN(ID_USUARIO)
       FROM USUARIOS
      WHERE UPPER(USU_EMAIL) = 'ADMIN.PRUEBA@RICALDONE.EDU.SV')
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM EMPLEADOS
    WHERE UPPER(EMP_CORREO) = 'ADMIN.PRUEBA@RICALDONE.EDU.SV'
);

INSERT INTO EMPLEADOS (
    EMP_NOMBRE,
    EMP_APELLIDO,
    EMP_CLAVE,
    EMP_CORREO,
    EMP_ROL,
    USUARIO_EMPLEADO
)
SELECT
    'Ricardo',
    'De Paz',
    'Prueba123*',
    'docente.prueba@ricaldone.edu.sv',
    'DOCENTE ACADÉMICO',
    (SELECT MIN(ID_USUARIO)
       FROM USUARIOS
      WHERE UPPER(USU_EMAIL) = 'DOCENTE.PRUEBA@RICALDONE.EDU.SV')
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM EMPLEADOS
    WHERE UPPER(EMP_CORREO) = 'DOCENTE.PRUEBA@RICALDONE.EDU.SV'
);

PROMPT === 4. Encargado, estudiante y su relación ===

INSERT INTO ENCARGADO (
    ENC_NOMBRE,
    ENC_APELLIDO,
    ENC_TELEFONO,
    ENC_TIPO
)
SELECT
    'María',
    'López',
    '7000-0001',
    'MADRE'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM ENCARGADO
    WHERE ENC_TELEFONO = '7000-0001'
);

INSERT INTO ESTUDIANTE (
    EST_NOMBRE,
    EST_APELLIDO,
    EST_GRADO,
    EST_SECCION,
    EST_ESPECIALIDAD,
    EST_CODIGO,
    ID_ACADEMICA,
    ID_GRADO,
    USUARIO_ESTUDIANTE
)
SELECT
    'David Eduardo',
    'Ramírez Escobar',
    'SEGUNDO AÑO',
    'A',
    'DESARROLLO DE SOFTWARE',
    'EST-PRUEBA-001',
    (SELECT MIN(ID_ACADEMICA)
       FROM ACADEMICA
      WHERE UPPER(ACADEMICA) = '2-A'),
    (SELECT MIN(ID_GRADO)
       FROM GRADO
      WHERE UPPER(GRADO) = 'SEGUNDO AÑO'),
    (SELECT MIN(ID_USUARIO)
       FROM USUARIOS
      WHERE UPPER(USU_EMAIL) = 'ESTUDIANTE.PRUEBA@RICALDONE.EDU.SV')
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM ESTUDIANTE
    WHERE UPPER(EST_CODIGO) = 'EST-PRUEBA-001'
);

INSERT INTO ESTUDIANTE_ENCARGADO (ID_ESTUDIANTE, ID_ENCARGADO)
SELECT
    (SELECT MIN(ID_ESTUDIANTE)
       FROM ESTUDIANTE
      WHERE UPPER(EST_CODIGO) = 'EST-PRUEBA-001'),
    (SELECT MIN(ID_ENCARGADO)
       FROM ENCARGADO
      WHERE ENC_TELEFONO = '7000-0001')
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM ESTUDIANTE_ENCARGADO EE
    JOIN ESTUDIANTE E
      ON E.ID_ESTUDIANTE = EE.ID_ESTUDIANTE
    JOIN ENCARGADO EN
      ON EN.ID_ENCARGADO = EE.ID_ENCARGADO
    WHERE UPPER(E.EST_CODIGO) = 'EST-PRUEBA-001'
      AND EN.ENC_TELEFONO = '7000-0001'
);

PROMPT === 5. Cita inicial para probar el flujo completo ===

INSERT INTO CITA_REUNION (
    ID_EMPLEADO,
    ID_ESTUDIANTE_ENCARGADO,
    CIT_MOTIVO,
    CIT_ESTADO,
    CIT_OBSERVACIONES,
    CIT_FECHA_REUNION
)
SELECT
    (SELECT MIN(ID_EMPLEADO)
       FROM EMPLEADOS
      WHERE UPPER(EMP_CORREO) = 'DOCENTE.PRUEBA@RICALDONE.EDU.SV'),
    (SELECT MIN(EE.ID_ESTUDIANTE_ENCARGADO)
       FROM ESTUDIANTE_ENCARGADO EE
       JOIN ESTUDIANTE E
         ON E.ID_ESTUDIANTE = EE.ID_ESTUDIANTE
       JOIN ENCARGADO EN
         ON EN.ID_ENCARGADO = EE.ID_ENCARGADO
      WHERE UPPER(E.EST_CODIGO) = 'EST-PRUEBA-001'
        AND EN.ENC_TELEFONO = '7000-0001'),
    'Revisión de avance académico',
    'PENDIENTE',
    'Cita creada por el script de datos de prueba.',
    TO_DATE('2026-09-15 09:00', 'YYYY-MM-DD HH24:MI')
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1
    FROM CITA_REUNION C
    JOIN EMPLEADOS EM
      ON EM.ID_EMPLEADO = C.ID_EMPLEADO
    JOIN ESTUDIANTE_ENCARGADO EE
      ON EE.ID_ESTUDIANTE_ENCARGADO = C.ID_ESTUDIANTE_ENCARGADO
    JOIN ESTUDIANTE E
      ON E.ID_ESTUDIANTE = EE.ID_ESTUDIANTE
    WHERE UPPER(EM.EMP_CORREO) = 'DOCENTE.PRUEBA@RICALDONE.EDU.SV'
      AND UPPER(E.EST_CODIGO) = 'EST-PRUEBA-001'
      AND C.CIT_FECHA_REUNION = TO_DATE('2026-09-15 09:00', 'YYYY-MM-DD HH24:MI')
      AND UPPER(C.CIT_MOTIVO) = 'REVISIÓN DE AVANCE ACADÉMICO'
);

COMMIT;

PROMPT === 6. Verificación de los datos creados ===

SELECT
    U.ID_USUARIO,
    U.USU_EMAIL,
    U.USU_ROL
FROM USUARIOS U
WHERE UPPER(U.USU_EMAIL) IN (
    'ADMIN.PRUEBA@RICALDONE.EDU.SV',
    'DOCENTE.PRUEBA@RICALDONE.EDU.SV',
    'ESTUDIANTE.PRUEBA@RICALDONE.EDU.SV'
)
ORDER BY U.ID_USUARIO;

SELECT
    E.EST_CODIGO,
    E.EST_NOMBRE || ' ' || E.EST_APELLIDO AS ESTUDIANTE,
    U.USU_EMAIL AS CORREO_DE_ACCESO,
    EN.ENC_NOMBRE || ' ' || EN.ENC_APELLIDO AS ENCARGADO,
    EE.ID_ESTUDIANTE_ENCARGADO
FROM ESTUDIANTE E
JOIN USUARIOS U
  ON U.ID_USUARIO = E.USUARIO_ESTUDIANTE
JOIN ESTUDIANTE_ENCARGADO EE
  ON EE.ID_ESTUDIANTE = E.ID_ESTUDIANTE
JOIN ENCARGADO EN
  ON EN.ID_ENCARGADO = EE.ID_ENCARGADO
WHERE UPPER(E.EST_CODIGO) = 'EST-PRUEBA-001';

SELECT
    C.ID_CITA,
    EM.EMP_NOMBRE || ' ' || EM.EMP_APELLIDO AS DOCENTE,
    E.EST_NOMBRE || ' ' || E.EST_APELLIDO AS ESTUDIANTE,
    C.CIT_MOTIVO,
    C.CIT_ESTADO,
    TO_CHAR(C.CIT_FECHA_REUNION, 'YYYY-MM-DD HH24:MI') AS FECHA_HORA
FROM CITA_REUNION C
JOIN EMPLEADOS EM
  ON EM.ID_EMPLEADO = C.ID_EMPLEADO
JOIN ESTUDIANTE_ENCARGADO EE
  ON EE.ID_ESTUDIANTE_ENCARGADO = C.ID_ESTUDIANTE_ENCARGADO
JOIN ESTUDIANTE E
  ON E.ID_ESTUDIANTE = EE.ID_ESTUDIANTE
WHERE UPPER(E.EST_CODIGO) = 'EST-PRUEBA-001'
ORDER BY C.ID_CITA;

PROMPT === Script finalizado correctamente ===
